# Generated by Django 6.0.8 on 2026-08-07 08:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, help_text='Ж: 1,500,000 - 2,000,000₮', max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Бүтэн цагийн'), ('part_time', 'Хагас цагийн'), ('remote', 'Зайнаас')], default='full_time', max_length=50)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('requirements', wagtail.fields.RichTextField(blank=True, help_text='Тавигдах шаардлага')),
                ('deadline', models.DateField(blank=True, help_text='Өргөдөл хүлээн авах эцсийн хугацаа', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
