# Generated by Django 6.0.8 on 2026-09-03 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Овог нэр')),
                ('email', models.EmailField(max_length=254, verbose_name='Имэйл')),
                ('phone', models.CharField(max_length=50, verbose_name='Утас')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Танилцуулга')),
                ('resume', models.FileField(upload_to='applications/%Y/%m/', verbose_name='CV / Резюме')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpage')),
            ],
            options={
                'verbose_name': 'Өргөдөл',
                'verbose_name_plural': 'Өргөдлүүд',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
