# Generated by Django 6.0.8 on 2026-09-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactpage_contactformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='category',
            field=models.CharField(blank=True, help_text='Ж: Тээвэр, Эрчим хүч, Ус, Үл хөдлөх хөрөнгө, Дата төв', max_length=100),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='featured',
            field=models.BooleanField(default=False, help_text='Хуудасны эхэнд тодруулж харуулах эсэх'),
        ),
    ]
