# Generated by Django 6.0.8 on 2026-09-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_projectitem_category_projectitem_featured'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Судиогийн танилцуулга хэсгийн зураг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='photographer_credit',
            field=models.CharField(blank=True, help_text='Ж: Зураг: Б.Бат', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Expertise card-ын дэвсгэр зураг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
