# Generated by Django 6.0.8 on 2026-09-10 07:43

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_aboutpage_hero_image_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('concept', 'Санаа/Concept'), ('in_progress', 'Хийгдэж байгаа'), ('completed', 'Дууссан')], default='completed', max_length=50)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Богино танилцуулга')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Дэлгэрэнгүй агуулга')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Хуудасны эхэн дэх бүтэн өргөн зураг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='detail_page',
            field=models.ForeignKey(blank=True, help_text='Сонголтоор: энэ картыг дэлгэрэнгүй хуудас руу холбоно', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.projectdetailpage'),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.projectdetailpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
