# Generated by Django 6.0.8 on 2026-08-13 05:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero хэсэгт харагдах том зураг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Мэргэжлийн баг хамт олон, инновацийн шийдэл', help_text='Гарчигийн доорх богино тайлбар', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Бид ирээдүйг хамтдаа бүтээж байна', help_text='Нүүр хуудасны гол гарчиг', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_heading',
            field=models.CharField(blank=True, default='Бидний тухай', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
