# Generated by Django 6.0.8 on 2026-09-01 03:51

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_image_homepage_hero_subtitle_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='people_heading',
            field=models.CharField(blank=True, default='Манай хамт олон', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='people_subheading',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='statement',
            field=models.CharField(blank=True, default='Бид ирээдүйг илүү сайхан болгодог', help_text='Нүүр хуудасны хамгийн дээд, жижиг statement мөр', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='years_heading',
            field=models.CharField(blank=True, default='Бид олон жилийн турш ирээдүйг илүү сайхан болгож ирсэн', max_length=255),
        ),
        migrations.CreateModel(
            name='IdeaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tag', models.CharField(blank=True, help_text='Ж: About, Careers', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, help_text='Ж: /about/', max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('quote', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_cards', to='home.homepage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
