# Generated by Django 6.0.8 on 2026-09-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_people_heading_homepage_people_subheading_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='story_image',
            field=models.ForeignKey(blank=True, help_text="'Бидний тухай' хэсэгт харагдах том зураг", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
