# Generated by Django 6.0.8 on 2026-09-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_story_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Hero хэсэгт автоматаар тоглох дэвсгэр видео (MP4, дуугүй, давтагдана). Байвал зурган дээр давамгайлна.', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero хэсэгт харагдах том зураг (hero_video байхгүй үед ашиглагдана)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
